### ISSUE TITLE
How to create a TriangleMeshGeometry in Rust?

### ISSUE THREAD

**Issue by iddm** [EmbarkStudios/physx-rs#207]
I need a clear way to create a triangle mesh geometry. It requires a mutable pointer to a struct we can't create:

https://docs.rs/physx/latest/physx/geometry/trait.TriangleMeshGeometry.html
https://docs.rs/physx-sys/latest/physx_sys/struct.PxTriangleMesh.html

As well as it is not clear how to fill in the data even if we could, and with what.

Can anyone please come up with a triangle example pull request?

**Comment by rlidwka** [comment]
I'm creating it the following way, here's TriangleMesh (`physics` is PhysicsFoundation):

https://github.com/rlidwka/bevy_physx/blob/c5f13c495627db1272f1cce5f0b694e942ec0eaa/src/assets.rs#L187-L210

And here's TriangleMeshGeometry (`mesh` is TriangleMesh from previous step):

https://github.com/rlidwka/bevy_physx/blob/c5f13c495627db1272f1cce5f0b694e942ec0eaa/src/components.rs#L146-L152

The snippets above are a pretty straightforward port of the physx documentation (I like PhysX 3 docs better, and nothing has really changed since then):

https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/Geometry.html#triangle-meshes

**Comment by rlidwka** [comment]
> Can you please help me once again? 

Can you link to a full repository with the code, or simplify it down, or preferably both?

Errors can happen for a lot of reasons (invalid geometry, non-unit quaternion as rotation, etc.). Typically they are shown in the error callback, but I can't verify it from the snippet above.

Do simple shapes (e.g. tetrahedron) with zero transforms work?

**Comment by rlidwka** [comment]
> I found the problem. It was my thinking that we could use the TriangleMesh with dynamic actors, but we don't.

Yeah physx doesn't support those. You may want to look into convex decomposition (with something like V-HACD) to break down triangle mesh into multiple convex ones.
