### ISSUE TITLE
Compile error with Xcode 11

### ISSUE THREAD

**Issue by repi** [EmbarkStudios/physx-rs#23]
Got a surprise update to Xcode 11 on my Mac today, which broke `physx-sys` C++ compilation:

```
PhysX/physx/source/foundation/include/unix/PsUnixIntrinsics.h:59:2: error: implicit use of sequentially-consistent atomic may incur stronger memory barriers than necessary [-Werror,-Watomic-implicit-seq-cst]
        __sync_synchronize();
        ^~~~~~~~~~~~~~~~~~
1 error generated.
```

This can be fixed by modifying the `physx-sys/PhysX/physx/source/compiler/cmake/mac/CMakeLists.txt` and adding `-Wno-atomic-implicit-seq-cst ` to the `SET(PHYSX_CXX_FLAGS` line.

Though as we bring in the PhysX SDK as a submodule we can't do that fix in this repo, and Nvidia doesn't merge PRs as they use Perforce internally so would take a while for that to get in and be able to update the submodule.

So what we would want to do is to add that compile option from our `build.rs`, tried doing something like this:

```Rust
        .define("CMAKE_CXX_FLAGS", "-Wno-atomic-implicit-seq-cst")
        .profile(build_mode)
        .build();
```

But looks like that doesn't work either, likely because the PhysX Mac CMake file just overwrites that setting: `SET(CMAKE_CXX_FLAGS ${PHYSX_CXX_FLAGS})`.

So seems we have a couple of non-ideal options:
1. Contribute a fix back to the [Nvidia repo](https://github.com/NVIDIAGameWorks/PhysX) and wait half a year for a new PhysX version to be released. Though hopefully they could merge in a fix earlier, but haven't done that before.
2. Don't submodule PhysX SDK, check in the huge SDK to this repo and modify and fix the specific file (`physx-sys/PhysX/physx/source/compiler/cmake/mac/CMakeLists.txt`).
3. Come up with another solution from our `build.rs` to make CMake add the compiler option. This would be ideal but not sure if there are any ways of doing it.

**Comment by tgolsson** [comment]
@repo I've solved this type of issue in three different ways depending on the complexity of the bug:

1) In some cases, I've simply yanked the whole CMakeLists out of the submodule and reseated it in my repository, updating all paths etc. Then I simply include that file, instead of the one in the submodule.

2) In some cases I've used `execute_process` to patch the submodule from my parent CMakeLists.txt. Sometimes by simply injecting a patched CMakeLists file, sometimes by using `sed` to edit the target file in place. This is a bit shit since it dirties the submodule, however.

3) You can use  `set_target_properties` to append compile flags on a per-target basis, something like `set_target_properties(TargetName PROPERTIES COMPILE_FLAGS "-Wno-atomic-implicit-seq-cst")`. However, this requires us to list all targets we want to do this for.

I think in this case, number 2 is probably easiest, and 3 most robust.

**Comment by repi** [comment]
Ah cool. Don't think #2 would work as it modifies the source directory which `build.rs` files are not allowed to do, `cargo publish` detects and fails on that.

Option 3 sounds like something it could be possible though, if Nvidia doesn't merge and publish the PR fix in a timely manner
